### ISSUE TITLE
Name of the Organisation

### ISSUE THREAD

**Issue by jakeatcencol** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#15]
@AbleVarghese Make your the organisation name conforms to Team-<firstName>

**Comment by AbleVarghese** [comment]
Update:
Name of the organisation has been changed to reflect your suggestion. @jakeatcencol 

Looking forward in receiving any such recommendations and suggestions during the course of this project. Thanks.

**Comment by AbleVarghese** [comment]
Please close this issue if the new name of the organisation is better. 
Thanks. @jakeatcencol
