### ISSUE TITLE
Adding the UI part of posting notes into the profile 

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#20]
User story : A student can post notes
#8

**Comment by derekpwwong** [comment]
This task is finished

**Comment by AbleVarghese** [comment]
@derekpwwong I cannot find the code in the central repo as of now. Are you planning to push the code into the central Repo.?? 

Also, In addition to that, please make sure you create separate branch for each of the features you are developing. It is important.

**Comment by AbleVarghese** [comment]
Please enter started- date and time, completed date and time and Actual hrs, and reason for any delays please. @derekpwwong

**Comment by derekpwwong** [comment]
---------1st comment-------- ( when a task starts)
Started now on 10/19/2016 at 6:00pm.

---------2nd comment-------- ( when a task is completed)
Completed now on 10/19/2016 at 9:00pm.

---------3rd comment-------- ( when a task is completed)
Total hours it took to finish the task(Actual hrs) - 3 Hours..
