### ISSUE TITLE
Implement the post notes entities to the database

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#21]
User story : A student can post notes 
#8

**Comment by AbleVarghese** [comment]
@Sabrina-Ahmed  Please enter started- date and time, completed date and time and Actual hrs, and reason for any delays please.

**Comment by Sabrina-Ahmed** [comment]
Start Task at :19/10/2016: 10:00p.m for an hour worked 

Starts Task at :20/10/2016: 10:00 p.m 
Ends Task at:20/10/2016:1.00 a.m

Total Time: 4 hours
