### ISSUE TITLE
Method to pull user related content

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#52]
#32

**Comment by Sabrina-Ahmed** [comment]
Iteration 3
User Story: A student can read the notes by navigating into other student's profile
Task: Method to pull user related content
Time estimated: 4 hours

Start date: 24/11/2016 10:00 p.m
End date: 24/11/2016 12:00 p.m

**Comment by Sabrina-Ahmed** [comment]
![userdoc1](https://cloud.githubusercontent.com/assets/17516548/20644246/6f57b914-b3fc-11e6-9bdd-283088d223d1.PNG)
![dynamicnav](https://cloud.githubusercontent.com/assets/17516548/20644248/73419766-b3fc-11e6-9dca-40b25c9ef4e0.PNG)
