### ISSUE TITLE
Querying the database to populate the "browse notes"

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#54]
#32

**Comment by Sabrina-Ahmed** [comment]
Iteration 3
User Story: A student can read the notes by navigating into other student's profile
Task: Querying the database to populate the "browse notes"
Time estimated:2  #hours

Start date:22/11/2016   10:30 p.m
End date:22/11/2016     12:15 p.m

**Comment by AbleVarghese** [comment]
Thanks for the completion. @Sabrina-Ahmed can you look into how to attach the code segment for this task to this task entry(as the prof. requires it). Thanks

**Comment by Sabrina-Ahmed** [comment]
![documentcontroller](https://cloud.githubusercontent.com/assets/17516548/20644251/8106d7d0-b3fc-11e6-8f47-2a8e4cace090.PNG)
