### ISSUE TITLE
Implement the Download interface sequences for the notes

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#57]
#31

**Comment by AbleVarghese** [comment]
@derekpwwong this task is not implemented.. please work on it. It's the UI for downloading notes.

**Comment by derekpwwong** [comment]
@AbleVarghese 
12/7/2016 10 PM - 12/8/2016  1AM
Total Duration 3 Hours
