### ISSUE TITLE
Method that downloads the note

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#59]
#31

**Comment by Sabrina-Ahmed** [comment]
Start Date:06/11/2016
End Date:06/11/2016

Time taken: 5 hours

**Comment by AbleVarghese** [comment]
@Sabrina-Ahmed Please mention why it took more than the time estimated.
Thanks.

**Comment by Sabrina-Ahmed** [comment]
Ok, i will.

**Comment by AbleVarghese** [comment]
@Sabrina-Ahmed I have referenced this task on the corresponding merge requests. Seems like a comment made on the 'pull request' itself(when you try to make the pull request) referencing the actual task(within the pull request comment section) is a good way to link the merged code(code segment of the task) to the actual task itself.  It shows the merged branches as shown above(please see the above comment.)

I do not know if there is an alternative/better way to do this or if @jakeatcencol would like to see it differently.

**Comment by Sabrina-Ahmed** [comment]
![downloadnotes](https://cloud.githubusercontent.com/assets/17516548/20654479/cd3e5ee8-b4e7-11e6-99f3-3cc28c11ff9c.PNG)

**Comment by Sabrina-Ahmed** [comment]
revise
Task:Method that download notes for Iteration 3
Start date: 26/11/2016
End date: 26/11/2016

Time :30 minutes
