### ISSUE TITLE
Implementing the User profile Interface

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#67]
#33

**Comment by derekpwwong** [comment]
---------1st comment-------- ( when a task starts)
Started now on 10/23/2016 at 12:59pm.

---------2nd comment-------- ( when a task is completed)
Completed now on 10/23/2016 at 7:33pm.

---------3rd comment-------- ( when a task is completed)
Total hours it took to finish the task(Actual hrs) - 3Hours..
