### ISSUE TITLE
Method to delete from server

### ISSUE THREAD

**Issue by AbleVarghese** [COMP231-Group02-ScrumProjectTeam/Group-02--NoteSharing-Application#68]
#10

**Comment by AbleVarghese** [comment]
Please enter started- date and time. @SethKaminski

**Comment by SethKaminski** [comment]
Started

**Comment by AbleVarghese** [comment]
@SethKaminski Please pick up the task from iteration-03.  Starting with the task you took up initially, before even considering the tasks other members picked up.

**Comment by Sabrina-Ahmed** [comment]
Sunday 04/12/2016
Start Time:5:00pm 
End time: 7;30 pm

User Story:A Student can remove the notes
Task :Method to delete from server

**Comment by Sabrina-Ahmed** [comment]
![delete](https://cloud.githubusercontent.com/assets/17516548/20888764/3c169a56-bace-11e6-925e-d9c3d2261234.PNG)
